version: "3"

services:
  api:
    build: .
    ports:
      - 4000:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist # Prevent overwriting the built files

    env_file:
      - .env
